// Production dry run for migrations 114–116 (docs/HANDOFF.md, standing rules 3–4).
//
//   node dry-run.mjs            → writes the dry-run SQL and prints its path
//   node dry-run.mjs --local    → also proves it on the local replica
//
// The generated SQL runs all three migrations inside ONE `DO` block and then
// raises. Postgres therefore rolls every statement back by construction — a
// dry run cannot leave anything behind, even if nobody remembers to type
// ROLLBACK. The expected outcome is an ERROR whose message starts with
//   HELP24_DRY_RUN_OK
// Any other error is a real failure in the migrations, reported before
// anything was applied.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const migrations = path.resolve(here, '../../migrations');
const FILES = ['114_trust_safety_schema.sql', '115_trust_safety_actions.sql', '116_trust_safety_enforcement.sql'];

/** The statements between a file's own BEGIN; and COMMIT; lines. */
function body(file) {
  const lines = fs.readFileSync(path.join(migrations, file), 'utf8').replace(/\r\n/g, '\n').split('\n');
  const begin = lines.findIndex((l) => l.trim() === 'BEGIN;');
  const commit = lines.findLastIndex((l) => l.trim() === 'COMMIT;');
  if (begin < 0 || commit <= begin) throw new Error(`${file}: expected one BEGIN; … COMMIT; block`);
  const text = lines.slice(begin + 1, commit).join('\n');
  const tag = `$m${file.slice(0, 3)}$`;
  if (text.includes(tag) || text.includes('$dry$')) throw new Error(`${file}: contains the wrapper tag ${tag}`);
  return { tag, text };
}

export function dryRunSql() {
  const parts = FILES.map(body);
  return [
    '-- GENERATED by supabase/tests/trust-safety/dry-run.mjs — do not edit.',
    '-- Expected result: ERROR  HELP24_DRY_RUN_OK … (everything rolled back).',
    'DO $dry$',
    'BEGIN',
    ...parts.map(({ tag, text }) => `  EXECUTE ${tag}\n${text}\n${tag};`),
    "  RAISE EXCEPTION 'HELP24_DRY_RUN_OK: 114, 115 and 116 applied cleanly inside one transaction and were rolled back';",
    'END',
    '$dry$;',
    '',
  ].join('\n');
}

const out = path.join(os.tmpdir(), 'help24-trust-safety-dry-run.sql');
fs.writeFileSync(out, dryRunSql());
console.log(`dry-run SQL written to ${out}`);

if (process.argv.includes('--local')) {
  const { withDatabase } = await import('./harness.mjs');
  await withDatabase(async (db) => {
    let message = '';
    try {
      await db.query(fs.readFileSync(out, 'utf8'));
    } catch (e) {
      message = e.message;
    }
    if (!message.startsWith('HELP24_DRY_RUN_OK')) throw new Error(`dry run did not complete: ${message || 'no error raised'}`);
    const { rows } = await db.query(
      "select count(*)::int as n from pg_class where relname in ('account_restrictions','moderation_actions')");
    if (rows[0].n !== 0) throw new Error('dry run left objects behind');
    console.log('local replica: all three migrations applied inside the DO block, raised HELP24_DRY_RUN_OK, and left nothing behind');
  }, { files: [] });
}
