#!/usr/bin/env node
/**
 * build_reference_seed.js — generates the reference-data migrations FROM the
 * bundled app assets.
 *
 * WHY THIS EXISTS
 * ---------------
 * The app ships a JSON copy of every reference dataset so its pickers work
 * offline and before any migration is applied. That means the same data lives
 * in two places, and if the two ever disagree the app resolves a stored value
 * one way and the server another — which is precisely the class of bug the
 * controlled vocabulary was introduced to eliminate.
 *
 * So they are not maintained twice. The JSON asset is the single source of
 * truth and this script emits the SQL. Adding a town, a trade, or an entire
 * country is one edit to one JSON file plus a re-run of this script.
 *
 *   node scripts/build_reference_seed.js
 *
 * Writes:
 *   supabase/migrations/088_locations_registry.sql
 *   supabase/migrations/089_professions_catalogue.sql
 *
 * Both are idempotent, additive, and safe to re-run against a live database.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ASSETS = path.join(ROOT, 'mobile-app', 'assets', 'data');
const MIGRATIONS = path.join(ROOT, 'supabase', 'migrations');

// ── SQL literal helpers ──────────────────────────────────────────────────────
const q = (v) =>
  v === undefined || v === null || v === '' ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;
const num = (v) => (v === undefined || v === null ? 'NULL' : String(v));
const bool = (v) => (v ? 'TRUE' : 'FALSE');
const arr = (v) =>
  !v || v.length === 0
    ? `'{}'`
    : `ARRAY[${v.map(q).join(', ')}]::TEXT[]`;

function readAsset(name) {
  return JSON.parse(fs.readFileSync(path.join(ASSETS, name), 'utf8'));
}

function assertUnique(rows, key, label) {
  const seen = new Set();
  for (const row of rows) {
    const value = row[key];
    if (seen.has(value)) throw new Error(`Duplicate ${label}: ${value}`);
    seen.add(value);
  }
}

// ── 088 · locations ──────────────────────────────────────────────────────────
function buildLocations() {
  const data = readAsset('locations_ke.json');
  const places = data.places;
  assertUnique(places, 'i', 'location id');

  const ids = new Set(places.map((p) => p.i));
  for (const p of places) {
    if (p.t === 'area' && !ids.has(p.p)) {
      throw new Error(`Area ${p.i} points at unknown parent ${p.p}`);
    }
  }

  const values = places
    .map(
      (p) =>
        `  (${q(p.i)}, ${q(p.n)}, ${q(p.t)}, ${q(p.p)}, ${q(p.c)}, ${bool(p.hq)}, ` +
        `${num(p.lat)}, ${num(p.lng)}, ${num(p.r ?? 300)}, ${arr(p.a)}, ${q(p.cc || data.country)})`
    )
    .join(',\n');

  const counties = new Set(places.map((p) => p.c)).size;
  const hqs = places.filter((p) => p.hq).length;

  return `-- =============================================================================
-- Migration 088 — Location registry (generated; do not hand-edit)
-- =============================================================================
-- GENERATED BY scripts/build_reference_seed.js FROM
--   mobile-app/assets/data/locations_ke.json
-- Re-run that script after editing the asset. Editing this file by hand makes
-- the app's bundled dataset and the server disagree, which is the one failure
-- mode a controlled vocabulary exists to prevent.
--
-- WHAT THIS REPLACES
-- ------------------
-- \`KenyaLocation.all\` — 37 hardcoded (city, area) pairs covering 17 towns, with
-- no counties, no coordinates, no aliases and no way to change without an app
-- release. Every town outside Nairobi and Mombasa was given a fabricated area
-- called "Town Centre" purely so the tuple could exist.
--
-- This seed carries ${places.length} places: all 47 county headquarters,
-- ${counties} counties, every major town, and the neighbourhoods of the large
-- urban centres. Coordinates are present only where a trustworthy one exists
-- (${places.filter((p) => p.lat != null).length} entries) — they are never
-- invented, because they drive "snap my GPS fix to the nearest town".
--
-- SAFE + ADDITIVE. Creates two new read-only tables. Touches no existing table,
-- adds no constraint to \`posts.location\`, and migrates no existing row:
--   * \`posts.location\` keeps holding the SAME display string it always has
--     ("Westlands, Nairobi" / "Naivasha"), so every existing post, every
--     \`ilike '%city%'\` filter and every card keeps working untouched;
--   * a FK from posts to locations is deliberately NOT added — it would reject
--     legacy rows and rows whose location came from GPS naming a place this
--     registry has never heard of, both of which are legitimate.
--
-- Adding a town later is ONE INSERT plus a version bump. No app release.
-- Adding a COUNTRY is a new asset file, a re-run of the generator, and rows
-- with a different country_code. No Flutter change.
--
-- Clients: SELECT only (anon + authenticated). Writes: service_role only.
-- Rollback: DROP TABLE public.locations; DROP TABLE public.registry_versions;
-- =============================================================================

-- ── Registry versions ───────────────────────────────────────────────────────
-- One row per reference dataset. Clients read THIS (a few bytes) before
-- deciding whether to pull a table of hundreds of rows, so the daily sync cost
-- stays flat as the datasets grow. Bump \`version\` whenever you change rows —
-- a client only re-downloads when the number goes up.
CREATE TABLE IF NOT EXISTS public.registry_versions (
  key        TEXT PRIMARY KEY,      -- 'locations:KE', 'professions:global'
  version    INT  NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.registry_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS registry_versions_read ON public.registry_versions;
CREATE POLICY registry_versions_read ON public.registry_versions
  FOR SELECT TO anon, authenticated
  USING (TRUE);

GRANT SELECT ON public.registry_versions TO anon, authenticated;

-- ── Locations ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.locations (
  id            TEXT PRIMARY KEY,      -- stable slug; NEVER rename
  name          TEXT NOT NULL,         -- display name ("Westlands")
  kind          TEXT NOT NULL DEFAULT 'town'
                CHECK (kind IN ('city', 'town', 'area')),
  -- Parent city for a neighbourhood. Self-referencing FK is intentional here
  -- (unlike posts.location): both sides are managed by this migration.
  parent_id     TEXT REFERENCES public.locations(id) ON DELETE SET NULL,
  county        TEXT NOT NULL DEFAULT '',
  is_county_hq  BOOLEAN NOT NULL DEFAULT FALSE,
  latitude      DOUBLE PRECISION,      -- NULL where no trustworthy value exists
  longitude     DOUBLE PRECISION,
  rank          INT  NOT NULL DEFAULT 300,   -- search/browse weight
  aliases       TEXT[] NOT NULL DEFAULT '{}',-- what people actually type
  country_code  TEXT NOT NULL DEFAULT 'KE',
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS locations_read ON public.locations;
CREATE POLICY locations_read ON public.locations
  FOR SELECT TO anon, authenticated
  USING (active);

GRANT SELECT ON public.locations TO anon, authenticated;
-- No INSERT/UPDATE/DELETE grants: only the backend (service_role) manages rows.

CREATE INDEX IF NOT EXISTS idx_locations_country ON public.locations (country_code) WHERE active;
CREATE INDEX IF NOT EXISTS idx_locations_parent  ON public.locations (parent_id);
CREATE INDEX IF NOT EXISTS idx_locations_county  ON public.locations (county);
-- Coordinate lookups back the "nearest town" snap when it is done server-side.
CREATE INDEX IF NOT EXISTS idx_locations_coords  ON public.locations (latitude, longitude)
  WHERE latitude IS NOT NULL;

-- ── Seed ────────────────────────────────────────────────────────────────────
-- Parents are inserted in the same statement as their children; Postgres checks
-- the self-FK per row against the same statement's inserts, so ordering within
-- this VALUES list does not matter.
--
-- ON CONFLICT DO UPDATE rather than DO NOTHING: this table has no user-authored
-- content to protect, and a re-run is how a corrected coordinate or a new alias
-- reaches an existing deployment.
INSERT INTO public.locations
  (id, name, kind, parent_id, county, is_county_hq, latitude, longitude, rank, aliases, country_code)
VALUES
${values}
ON CONFLICT (id) DO UPDATE SET
  name         = EXCLUDED.name,
  kind         = EXCLUDED.kind,
  parent_id    = EXCLUDED.parent_id,
  county       = EXCLUDED.county,
  is_county_hq = EXCLUDED.is_county_hq,
  latitude     = EXCLUDED.latitude,
  longitude    = EXCLUDED.longitude,
  rank         = EXCLUDED.rank,
  aliases      = EXCLUDED.aliases,
  country_code = EXCLUDED.country_code,
  updated_at   = NOW();

INSERT INTO public.registry_versions (key, version)
VALUES ('locations:${data.country}', ${data.version})
ON CONFLICT (key) DO UPDATE SET
  version    = GREATEST(public.registry_versions.version, EXCLUDED.version),
  updated_at = NOW();

COMMENT ON TABLE public.locations IS
  'Location vocabulary (${places.length} places, ${counties} counties, ${hqs} county HQs). Generated from mobile-app/assets/data/locations_ke.json by scripts/build_reference_seed.js. Add a town with one INSERT plus a registry_versions bump — no app release.';
COMMENT ON COLUMN public.locations.latitude IS
  'NULL where no trustworthy coordinate exists. Only non-null rows are candidates for snapping a GPS fix to the nearest known town.';
COMMENT ON TABLE public.registry_versions IS
  'One row per reference dataset. Clients read this before pulling a whole table, so sync cost stays flat as the datasets grow.';
`;
}

// ── 089 · professions ────────────────────────────────────────────────────────
function buildProfessions() {
  const data = readAsset('professions.json');
  const { categories, professions } = data;
  assertUnique(categories, 'i', 'profession category id');
  assertUnique(professions, 'i', 'profession id');

  const names = professions.map((p) => p.n.toLowerCase());
  const dupName = names.find((n, i) => names.indexOf(n) !== i);
  if (dupName) throw new Error(`Duplicate profession name: ${dupName}`);

  const categoryIds = new Set(categories.map((c) => c.i));
  for (const p of professions) {
    if (!categoryIds.has(p.g)) throw new Error(`${p.i} references unknown category ${p.g}`);
  }

  // The seventeen ids seeded by migration 086. They already sit in
  // users.profession on live rows, so the catalogue MUST still contain every
  // one of them — a missing id would turn a completed profile into an
  // unconfirmed one overnight.
  const LEGACY = ['electrician','plumber','mechanic','cleaner','tutor','driver','welder','builder','painter','carpenter','it-technician','photographer','salon-beauty','tailor','cook','moving-services','other'];
  const ids = new Set(professions.map((p) => p.i));
  const missing = LEGACY.filter((id) => !ids.has(id));
  if (missing.length) throw new Error(`Catalogue drops migration-086 ids: ${missing.join(', ')}`);

  const categoryValues = categories
    .map((c) => `  (${q(c.i)}, ${q(c.n)}, ${q(c.icon)}, ${num(c.s)}, ${arr(c.t)})`)
    .join(',\n');

  const professionValues = professions
    .map(
      (p) =>
        `  (${q(p.i)}, ${q(p.n)}, ${q(p.icon)}, ${q(p.g)}, ${q(p.c)}, ` +
        `${arr(p.a)}, ${arr(p.t)}, ${num(p.w ?? 500)}, ${q(p.cc)})`
    )
    .join(',\n');

  return `-- =============================================================================
-- Migration 089 — Profession catalogue (generated; do not hand-edit)
-- =============================================================================
-- GENERATED BY scripts/build_reference_seed.js FROM
--   mobile-app/assets/data/professions.json
-- Re-run that script after editing the asset.
--
-- WHAT THIS REPLACES
-- ------------------
-- Migration 086 established the controlled vocabulary and seeded it with 17
-- trades in one flat list. That was the right shape and the wrong size: a
-- marketplace cannot describe its supply side with seventeen words, and a flat
-- list stops being browsable long before it stops growing.
--
-- This migration takes the catalogue to ${professions.length} professions across
-- ${categories.length} categories, adds the aliases people actually type
-- (including Kiswahili — "fundi", "mama fua", "boda"), and adds the tags that
-- cut across the taxonomy (white collar / blue collar / freelance / emerging).
--
-- BACKWARD COMPATIBILITY IS ABSOLUTE
-- ----------------------------------
--   * All 17 ids from 086 are still present with their exact names, so every
--     value already stored in \`users.profession\` still resolves;
--   * the ON CONFLICT clause updates only the NEW columns on those rows — an
--     admin's edit to a name, icon, sort or active flag is never clobbered;
--   * \`users.profession\` gains no constraint, exactly as in 086: legacy free
--     text keeps rendering verbatim and simply counts as an incomplete field.
--
-- Self-sufficient: it creates \`professions\` and \`registry_versions\` if 086 or
-- 088 have not been applied yet, so these migrations can be applied in any
-- order or independently.
--
-- ONE WAY THIS CAN FAIL LOUDLY (and safely): \`professions.name\` is UNIQUE from
-- 086. If an admin has manually added a row whose NAME collides with one of the
-- new ids below, the whole statement aborts in its transaction and nothing
-- changes. Rename the manual row, then re-run.
--
-- Clients: SELECT only (anon + authenticated). Writes: service_role only.
-- Rollback: DROP TABLE public.profession_categories;
--           ALTER TABLE public.professions DROP COLUMN group_id, ...;
-- =============================================================================

-- ── Registry versions (no-op when 088 already ran) ──────────────────────────
CREATE TABLE IF NOT EXISTS public.registry_versions (
  key        TEXT PRIMARY KEY,
  version    INT  NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.registry_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS registry_versions_read ON public.registry_versions;
CREATE POLICY registry_versions_read ON public.registry_versions
  FOR SELECT TO anon, authenticated
  USING (TRUE);

GRANT SELECT ON public.registry_versions TO anon, authenticated;

-- ── Base table (no-op when 086 already ran) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.professions (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  icon        TEXT,
  sort        INT  NOT NULL DEFAULT 100,
  active      BOOLEAN NOT NULL DEFAULT TRUE,
  category_id TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.professions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS professions_read ON public.professions;
CREATE POLICY professions_read ON public.professions
  FOR SELECT TO anon, authenticated
  USING (active);

GRANT SELECT ON public.professions TO anon, authenticated;

-- ── Categories ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profession_categories (
  id         TEXT PRIMARY KEY,          -- stable slug ("skilled-trades")
  name       TEXT NOT NULL,
  icon       TEXT,                      -- inherited by professions with no icon
  sort       INT  NOT NULL DEFAULT 500,
  tags       TEXT[] NOT NULL DEFAULT '{}',
  active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.profession_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profession_categories_read ON public.profession_categories;
CREATE POLICY profession_categories_read ON public.profession_categories
  FOR SELECT TO anon, authenticated
  USING (active);

GRANT SELECT ON public.profession_categories TO anon, authenticated;

-- ── New profession columns ──────────────────────────────────────────────────
-- Deliberately NOT a foreign key to profession_categories: a profession whose
-- category row is missing must still be selectable (it falls into the app's
-- "Other" grouping), and a category rename must never block a profession
-- insert. Same reasoning as category_id in 086.
ALTER TABLE public.professions
  ADD COLUMN IF NOT EXISTS group_id     TEXT NOT NULL DEFAULT 'other',
  ADD COLUMN IF NOT EXISTS aliases      TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS tags         TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS weight       INT NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS country_code TEXT;

CREATE INDEX IF NOT EXISTS idx_professions_group ON public.professions (group_id) WHERE active;

-- ── Seed: categories ────────────────────────────────────────────────────────
INSERT INTO public.profession_categories (id, name, icon, sort, tags) VALUES
${categoryValues}
ON CONFLICT (id) DO UPDATE SET
  name       = EXCLUDED.name,
  icon       = EXCLUDED.icon,
  sort       = EXCLUDED.sort,
  tags       = EXCLUDED.tags,
  updated_at = NOW();

-- ── Seed: professions ───────────────────────────────────────────────────────
-- ON CONFLICT updates ONLY the columns this migration introduces. name, icon,
-- sort, active and category_id are left exactly as they are, so the 17 rows
-- from 086 gain their taxonomy without losing anything, and any later admin
-- edit survives a re-run.
INSERT INTO public.professions
  (id, name, icon, group_id, category_id, aliases, tags, weight, country_code)
VALUES
${professionValues}
ON CONFLICT (id) DO UPDATE SET
  group_id     = EXCLUDED.group_id,
  aliases      = EXCLUDED.aliases,
  tags         = EXCLUDED.tags,
  weight       = EXCLUDED.weight,
  country_code = EXCLUDED.country_code,
  updated_at   = NOW();

INSERT INTO public.registry_versions (key, version)
VALUES ('professions:global', ${data.version})
ON CONFLICT (key) DO UPDATE SET
  version    = GREATEST(public.registry_versions.version, EXCLUDED.version),
  updated_at = NOW();

COMMENT ON TABLE public.profession_categories IS
  'Profession taxonomy (${categories.length} categories). Generated from mobile-app/assets/data/professions.json by scripts/build_reference_seed.js.';
COMMENT ON COLUMN public.professions.aliases IS
  'What people actually type, including Kiswahili and local terms. The highest-value field for search recall.';
COMMENT ON COLUMN public.professions.tags IS
  'Cross-cutting labels (wc/bc/fl/em). Empty means inherit the category tags.';
COMMENT ON COLUMN public.professions.weight IS
  'Search tiebreak. Higher surfaces first when several titles match a query equally well.';
`;
}

// ── Run ──────────────────────────────────────────────────────────────────────
function main() {
  const outputs = [
    ['088_locations_registry.sql', buildLocations()],
    ['089_professions_catalogue.sql', buildProfessions()],
  ];
  for (const [name, sql] of outputs) {
    const target = path.join(MIGRATIONS, name);
    fs.writeFileSync(target, sql, 'utf8');
    const lines = sql.split('\n').length;
    console.log(`wrote ${path.relative(ROOT, target)} (${lines} lines)`);
  }
}

main();
