// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACUqU_xmKi1fmxfmu2IkokFvlLGOaZ8u0',
    appId: '1:454215745233:web:9d4ec935f8d80842aa4ff0',
    messagingSenderId: '454215745233',
    projectId: 'help24-24410',
    authDomain: 'help24-24410.firebaseapp.com',
    storageBucket: 'help24-24410.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzNruj2eqXtK75Y9cP6Gcf0uZZTAod9E',
    appId: '1:454215745233:android:4b262becc88b5563aa4ff0',
    messagingSenderId: '454215745233',
    projectId: 'help24-24410',
    storageBucket: 'help24-24410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYL65pS4NlHuY3NuajwD9-vSko4a7VFK0',
    appId: '1:454215745233:ios:2001c38b12d5dc82aa4ff0',
    messagingSenderId: '454215745233',
    projectId: 'help24-24410',
    storageBucket: 'help24-24410.firebasestorage.app',
    iosClientId: '454215745233-u5cclbv3q4o801j9qvmabva73p5tquv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.help24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYL65pS4NlHuY3NuajwD9-vSko4a7VFK0',
    appId: '1:454215745233:ios:2001c38b12d5dc82aa4ff0',
    messagingSenderId: '454215745233',
    projectId: 'help24-24410',
    storageBucket: 'help24-24410.firebasestorage.app',
    iosClientId: '454215745233-u5cclbv3q4o801j9qvmabva73p5tquv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.help24',
  );
}
